log:
  disable_sentry: true
  level: "info"

db:
  url: "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable"

listener:
  addr: :9101

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: customer-service
  service_port: 80
