log:
  disable_sentry: true
  level: "info"

db:
  url: "postgres://postgres:postgres@customer-db/postgres?sslmode=disable"
# Uncomment to use locally:
#  url: "postgres://postgres:postgres@localhost:5435/postgres?sslmode=disable"

listener:
  addr: :9101


# if docker false, the first entry point will be used, otherwise the second!!!
endpoints:
  docker: false
  services:
    - service: "auth-service"
      entry_points:
        - "localhost:9110/jwt/login"
        - "auth-service:9110/jwt/login"
    - service: "staff-service"
      entry_points:
        - "localhost:9102/jwt/user"
        - "staff-service:9102/jwt/user"

cop:
  disabled: true



