version: '3.3'

services:
  customer-service:
    restart: unless-stopped
    build: .
    ports:
      - "9101:9101"
    depends_on:
      - customer_db
    environment:
      - KV_VIPER_FILE=/config.yaml
      - AUTH_SERVICE=http://127.0.0.1:9110/jwt/login
    volumes:
      - ./config.yaml:/config.yaml
    entrypoint: sh -c "customer-service migrate up && customer-service run service"

  customer_db:
    image: postgres
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/data/pgdata
      - ENSUREDB=1
    volumes:
      - database_data:/var/lib/postgresql/data


  db2:
    image: postgres
    restart: always
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/data/pgdata
      - ENSUREDB=1
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local